version: '3.7'

services:
#  frontend:
#    build:
#      context: ./src/client
#      dockerfile: Dockerfile
#    ports:
#      - "3000:80" # Map container port 80 to host port 3000
#    depends_on:
#      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Map container port 8080 to host port 8080
    environment:
      SPRING_DATA_MONGODB_HOST: mongodbhost
      SPRING_DATA_MONGODB_URI: mongodb://admin:password@mongodbhost:27017/mongoDB?authSource=admin&authMechanism=SCRAM-SHA-1&maxIdleTimeMS=3000&keepAlive=true
    depends_on:
      - mongo

  mongo:
    image: mongo:3.6.23
    #    platform: linux/amd64
    restart: unless-stopped
    container_name: docker-mymongo
    hostname: mongodbhost
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: mongoDB
    ports:
      - "27017:27017"


